name: Publish Nar artefacts to Maven Central
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - # TODO remove
      - 'test-publish-**'
jobs:
  build:
    name: Publish artefacts
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Execute Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x test
      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: Sign artefacts
        uses: gradle/gradle-build-action@v2
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        with:
          arguments: signMavenJavaPublication
      - name: Publish, close and release
        uses: gradle/gradle-build-action@v2
        env:
          # publishToSonatype will trigger repeated signMavenJavaPublication, so include that credentials again...
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
        with:
          # TODO replace
          arguments: publishToSonatype
#          arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository
